GET http://localhost:3000/content

###
POST http://localhost:3000/content HTTP/1.1 

content-type: application/json;
{
    "title": "Testing",
    "content": "This is the Content Page",
    "page": "Hello World",
    "image": "Hard coded image text would go here",
    
}